pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t django-app:latest .'
            }
        }

        stage('Database Migration') {
            steps {
                sh 'docker run --rm django-app:latest python manage.py migrate'
            }
        }

        stage('Run Django') {
            steps {
                sh '''
                    docker stop django-app || true
                    docker rm django-app || true

                    docker run -d \
                        --name django-app \
                        -p 8000:8000 \
                        django-app:latest
                '''
            }
        }
    }
}
