pipeline {
    agent none
    stages {

        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.9.1-eclipse-temurin-11'
                }
            }
            steps {
                sh 'mvn --version'
            }
        }

        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }

        stage('DB') {
            agent {
                docker {
                    image 'mysql:8.0'
                }
            }
            steps {
                sh 'mysql --version'
            }
        }
    }
}
